version: "3"
services:
  postgres:
    image: postgres:12.2
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=appus
         - POSTGRES_USER=appus
         - POSTGRES_DB=appus
    restart: unless-stopped

  app:
    image: desafioappus:0.1
    network_mode: bridge
    container_name: desafioappus
    expose:
      - 8080
    ports:
      - 8081:8080
    volumes:
          - C:/_projects/vbsolutions/pessoal/Appus/DesafioAppus:/var/tmp
    restart: unless-stopped
volumes:
  postgres-data: